# .github/workflows/file-update-trigger.yml
name: Trigger on File Update and Manual Dispatch

on:
  push:
    paths:
      - digiaTestcheck.txt  # Trigger when this specific file is updated
  workflow_dispatch:        # Enable manual trigger

jobs:
  run-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run some task
        run: echo "File updated or manually triggered, running task..."
